services:
  backend:
    build: ./backend/functionality
    ports:
      - "5001:5001"
    env_file:
      - ./backend/functionality/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "81:81"
    environment:
      - VITE_API_BASE_URL=http://35.210.202.5/5001
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  db:
    image: mysql:8
    ports:
      - "3301:3306"
    volumes:
      - team-1-project_db_data:/var/lib/mysql

volumes:
  team-1-project_db_data:
