services:
  backend:
    build: ./backend/functionality
    ports:
      - "5001:5001"
    env_file:
      - ./backend/functionality/.env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "81:81"
    environment:
      - VITE_API_BASE_URL=http://35.210.202.5:5001
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  db:
    image: mysql:8
    ports:
      - "3301:3306"
    env_file:
      - ./backend/functionality/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DB:-oneskyv1}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - team-1-project_db_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  team-1-project_db_data:
