services:
  backend:
    build: ./backend/functionality
    ports:
      - "5001:5001"
    env_file:
      - ./backend/functionality/.env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=onesky
      - MYSQL_PASSWORD=secretsecret1
      - MYSQL_DB=oneskyv1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - onesky-network

  frontend:
    build: ./frontend
    ports:
      - "81:81"
    environment:
      - VITE_API_BASE_URL=http://35.210.202.5:5001
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - onesky-network

  db:
    image: mysql:8
    ports:
      - "3301:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secretsecret1
      - MYSQL_USER=onesky
      - MYSQL_PASSWORD=secretsecret1
      - MYSQL_DATABASE=oneskyv1
    volumes:
      - onesky-project_db_dataproject_db_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uonesky", "-psecretsecret1"]
      timeout: 20s
      retries: 20
      interval: 5s
      start_period: 30s
    networks:
      - onesky-network

volumes:
  onesky-project_db_data:

networks:
  onesky-network:
    driver: bridge
