services:
  backend:
    build: ./backend/functionality
    ports:
      - "5001:5001"
    env_file:
      - ./backend/functionality/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "81:81"
    environment:
      - VITE_API_BASE_URL=http://35.210.202.5:5001
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  db:
    image: mysql:8
    ports:
      - "3301:3306"
    env_file:
      - ./backend/functionality/.env
    environment:
      - MYSQL_HOST=35.210.202.5
      - MYSQL_PORT=3301
      - MYSQL_USER=onesky
      - MYSQL_PASSWORD=secretsecret1
      - MYSQL_DATABASE=oneskyv1
    volumes:
      - team-1-project_db_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  team-1-project_db_data:
